version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/moznion/gowrtr
    steps:
      - checkout
      - run: make bootstrap
      - run: make ci-check
      - run: bash <(curl -s https://codecov.io/bash)

